CREATE DATABASE MyDB
ON
PRIMARY
 (NAME = MyDB_Prm,
 FILENAME = 'E:\max\Programming\05_T-SQL_Yamshikov\ITMO.Y2020.Group124.TSQL-LABS\LAB_CREATE_MyDB\MyDB_Prm.mdf',
 SIZE = 8MB,
 MAXSIZE = 16MB,
 FILEGROWTH = 8MB),

 FILEGROUP MyDB_FG1
 (NAME = MyDB_FG1_1,
 FILENAME = 'E:\max\Programming\05_T-SQL_Yamshikov\ITMO.Y2020.Group124.TSQL-LABS\LAB_CREATE_MyDB\MyDB_FG1_1.ndf',
 SIZE = 1MB,
 MAXSIZE = 8MB,
 FILEGROWTH = 4MB),

 (NAME = MyDB_FG1_2,
 FILENAME = 'E:\max\Programming\05_T-SQL_Yamshikov\ITMO.Y2020.Group124.TSQL-LABS\LAB_CREATE_MyDB\MyDB_FG1_2.ndf',
 SIZE = 1MB,
 MAXSIZE = 8MB,
 FILEGROWTH = 4MB)

 LOG ON 
 (NAME = MyDB,
 FILENAME = 'E:\max\Programming\05_T-SQL_Yamshikov\ITMO.Y2020.Group124.TSQL-LABS\LAB_CREATE_MyDB\MyDB.idf',
 SIZE = 1MB,
 MAXSIZE = 8MB,
 FILEGROWTH = 4MB)
 GO

 ALTER DATABASE MyDB 
  MODIFY FILEGROUP MyDB_FG1 DEFAULT;
GO


--DROP DATABASE MyDB;
--GO